version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install -g serverless
  build:
    on-failure: ABORT
    commands:
      - sls deploy

