service: backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
  stage: dev
  region: ap-northeast-1
  profile: default


  httpApi:
    cors: true


# you can define service wide environment variables here
  environment:
    CHECK_LIST: Oracle Google Microsoft Amazon Deloitte

functions:
  process:
    handler: handler.process
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - httpApi:
          path: /create
          method: put

